### ISSUE TITLE
Create docker-compose with volume mount

### ISSUE THREAD

**Issue by finnless** [Open-Book-Genome-Project/sequencer#74]
Reference code from Open Library:

**[openlibrary/docker-compose.production.yml](https://github.com/internetarchive/openlibrary/blob/71fc029f56f4300ccbea1060c3ff81f7d168e275/docker-compose.production.yml#L8-L22)**
Lines 8 to 22 in https://github.com/internetarchive/openlibrary/commit/71fc029f56f4300ccbea1060c3ff81f7d168e275
```yml
version: "3.1"
services:
  web:
    profiles: ["ol-web1", "ol-web2"]
    image: "${OLIMAGE:-openlibrary/olbase:latest}"
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - GUNICORN_OPTS= --workers 50 --timeout 300 --max-requests 500
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
      - BEFORE_START=pip install -e /booklending_utils
    volumes:
      - ../booklending_utils:/booklending_utils
      - ../olsystem:/olsystem
      - ../olsystem/etc/ia.ini:/home/openlibrary/.config/ia.ini
```
